// H3 CLI integration tests.
//
// These tests spawn the converter as a subprocess via `assert_cmd` and
// poke at the H3 surface area:
//
//   * The disk-stdout gate (env-var override, IsTerminal refusal,
//     HISTCONTROL/HISTFILE history-safety check).
//   * Clap's mutually-exclusive flag rejection.
//   * The `--inspect-only` short-circuit + redacted-key marker.
//   * Mask-by-default in describe_blob.
//
// All AES-256 tests use `tests/data/toy_2of3.txt`; AES-128 / AES-192 tests
// use `toy_2of3_aes128.txt` / `toy_2of3_aes192.txt`. All three are
// deterministic 2-of-3 toy share sets generated by `cargo run --bin
// gen_fixture` (see the header in `src/bin/gen_fixture.rs` for the
// per-key-length seed contract and regeneration commands). The legacy
// real fixture was deleted; this repo no longer contains any key bytes
// that have ever existed on a real HSM.

use assert_cmd::Command;
use predicates::prelude::*;

/// M-C3: generic fixture loader. `name` is the basename of a file under
/// `tests/data/` (e.g. `"toy_2of3.txt"`, `"toy_2of3_aes128.txt"`).
/// Panics with the resolved path if the file is missing — this signals a
/// missing committed fixture, not an I/O race.
fn load_fixture(name: &str) -> Vec<u8> {
    let mut path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("tests/data");
    path.push(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("missing fixture {path:?}: {e}"))
}

/// Common: clear all `HIST*` env-vars on the child so the gate sees a
/// pristine environment. The default cargo-test harness inherits the
/// host's HISTFILE and friends, which would derail the gate logic.
fn cmd() -> Command {
    let mut c = Command::cargo_bin("yubihsm-share-converter").unwrap();
    c.env_remove("HISTFILE")
        .env_remove("HISTCONTROL")
        .env_remove("YHSC_ALLOW_DISK_STDOUT");
    c
}

// ─────────────────────── disk-stdout gate ──────────────────────────────

#[test]
fn resplit_without_tty_or_env_var_refuses_with_exit_6() {
    // assert_cmd captures stdout and so stdout is *not* a TTY in the
    // child; YHSC_ALLOW_DISK_STDOUT is unset (cmd() removed it). The
    // converter must refuse with exit code 6 before reading stdin.
    // M-3-2: error message updated to name which key-bearing stream
    // is non-TTY (stdout for --resplit, stderr for --show-key).
    let toy = load_fixture("toy_2of3.txt");
    cmd()
        .arg("--resplit")
        .write_stdin(toy)
        .assert()
        .code(6)
        .stderr(predicate::str::contains(
            "a key-bearing stream is not a terminal",
        ))
        .stderr(predicate::str::contains("stdout = non-tty (pipe/file)"));
}

#[test]
fn resplit_with_env_var_and_unset_histfile_succeeds() {
    // HISTFILE is unset → hist_disabled = true → gate accepts the
    // YHSC_ALLOW_DISK_STDOUT=1 override. R4-3: the dual-knob gate now
    // also requires --i-accept-disk-output on the command line; without
    // it this test would exit 6 even with the env-var set. The converter
    // then re-splits and emits 3 hex-share lines on stdout.
    let toy = load_fixture("toy_2of3.txt");
    let assert = cmd()
        .arg("--resplit")
        .arg("--i-accept-disk-output")
        .env("YHSC_ALLOW_DISK_STDOUT", "1")
        .write_stdin(toy)
        .assert()
        .success();

    let out = String::from_utf8(assert.get_output().stdout.clone()).expect("stdout is utf-8");
    let share_lines: Vec<&str> = out
        .lines()
        .filter(|l| {
            // T-X-hex format: starts with `2-<digit>-`, rest is hex.
            l.len() >= 4
                && l.as_bytes()[0] == b'2'
                && l.as_bytes()[1] == b'-'
                && l.as_bytes()[3] == b'-'
                && l.as_bytes()[2].is_ascii_digit()
        })
        .collect();
    assert_eq!(
        share_lines.len(),
        3,
        "expected 3 hex share lines, got: {out:?}"
    );
    for line in &share_lines {
        // Per yubihsm-manager regex: hex tail is [0-9a-f].
        let tail = &line[4..];
        assert!(
            tail.bytes().all(|b| b.is_ascii_hexdigit()),
            "share tail {tail:?} is not pure hex"
        );
    }
}

#[test]
fn env_var_set_with_unsafe_history_refuses_with_exit_8() {
    // HISTFILE points somewhere AND HISTCONTROL has no `ignorespace` /
    // `ignoreboth` → gate hard-refuses. The exit code is 8 and the
    // error message names the override modes.
    let toy = load_fixture("toy_2of3.txt");
    cmd()
        .arg("--resplit")
        .env("YHSC_ALLOW_DISK_STDOUT", "1")
        .env("HISTFILE", "/home/whoever/.bash_history")
        .env("HISTCONTROL", "")
        .write_stdin(toy)
        .assert()
        .code(8)
        .stderr(predicate::str::contains("shell history would"));
}

// ─────────────────────── clap mutex ────────────────────────────────────

#[test]
fn resplit_plus_inspect_only_is_rejected_by_clap() {
    // Clap rejects mutually-exclusive flag combinations with its own
    // exit code (currently 2). The exact code is owned by clap; we
    // assert non-zero + a recognisable error fragment instead of
    // pinning the number, so a future clap upgrade doesn't break us.
    cmd()
        .arg("--resplit")
        .arg("--inspect-only")
        .assert()
        .failure()
        .stderr(predicate::str::contains("cannot be used with"));
}

// ─────────────────────── inspect-only short-circuit ────────────────────

#[test]
fn inspect_only_prints_marker_and_no_stdout() {
    let toy = load_fixture("toy_2of3.txt");
    let assert = cmd()
        .arg("--inspect-only")
        .write_stdin(toy)
        .assert()
        .success()
        .stderr(predicate::str::contains("[inspect-only]"))
        .stderr(predicate::str::contains("recovery succeeded"));

    // Stdout must be empty: no key bytes, no share lines, no banner.
    assert_eq!(
        assert.get_output().stdout.len(),
        0,
        "inspect-only must produce no stdout, got {:?}",
        String::from_utf8_lossy(&assert.get_output().stdout)
    );
}

// ─────────────────────── mask-by-default ───────────────────────────────

#[test]
fn default_run_masks_aes_key_in_describe_blob() {
    // No flags → describe_blob runs but the AES key is replaced with a
    // `<redacted: ... bytes; pass --show-key to print>` marker on
    // stderr. The fabricated toy blob has wrap_id 0xa5a2 (we don't
    // assert that here; we only assert the redaction).
    //
    // stdout is also not a TTY in this child, but we passed neither
    // --resplit nor --show-key, so the gate is *not* triggered (that
    // path is just for key-bearing output). The default flow still
    // succeeds.
    let toy = load_fixture("toy_2of3.txt");
    let assert = cmd().write_stdin(toy).assert().success();

    let stderr = String::from_utf8(assert.get_output().stderr.clone()).expect("stderr is utf-8");
    assert!(
        stderr.contains("<redacted"),
        "default run must redact the AES key; got stderr:\n{stderr}"
    );
    // The toy fixture's AES key bytes (from the deterministic blob) are
    // bytes 20..52 of `(i*7)^0xA5`. The first key byte is (20*7)^0xA5
    // = 140 ^ 165 = 41 = 0x29; second is (21*7)^0xA5 = 147 ^ 165 = 50
    // = 0x32. So a leak would print "2932..." on the aes256_key line.
    // We assert the leak prefix is *absent*.
    assert!(
        !stderr.contains("aes256_key (hex)   = 2932"),
        "default run leaked the toy AES key prefix; stderr:\n{stderr}"
    );
    // Stdout must be empty in the default (no --resplit) flow.
    assert_eq!(
        assert.get_output().stdout.len(),
        0,
        "default run with no flags should produce no stdout"
    );
}

// ─────────────────────── M-C3: AES-128 / AES-192 round-trip ────────────
//
// The AES-256 path is exercised across the rest of this file via
// `toy_2of3.txt` (52-byte blob). M-C3 adds two committed sibling
// fixtures, one per remaining AES variant, and round-trips them through
// the same `--inspect-only` short-circuit. Stderr fragments are pinned
// against the exact byte/key-length banner emitted by `describe_blob`
// in src/main.rs so a regression that returned the wrong key length —
// e.g. dropping the trailing 4 bytes off an AES-192 blob — fails here
// even if recovery itself silently "succeeds".

#[test]
fn inspect_only_round_trips_aes128() {
    let toy = load_fixture("toy_2of3_aes128.txt");
    cmd()
        .arg("--inspect-only")
        .write_stdin(toy)
        .assert()
        .success()
        .stderr(predicate::str::contains("36 bytes (16-byte AES key)"))
        .stderr(predicate::str::contains("recovery succeeded"));
}

#[test]
fn inspect_only_round_trips_aes192() {
    let toy = load_fixture("toy_2of3_aes192.txt");
    cmd()
        .arg("--inspect-only")
        .write_stdin(toy)
        .assert()
        .success()
        .stderr(predicate::str::contains("44 bytes (24-byte AES key)"))
        .stderr(predicate::str::contains("recovery succeeded"));
}

// ─────────────────────── M-3-1: env-var truthy semantics ───────────────
//
// Pre-fix, `YHSC_ALLOW_DISK_STDOUT=0` and `YHSC_ALLOW_DISK_STDOUT=` both
// engaged the disk-stdout override (presence-only via `var_os(...).is_some()`).
// Post-fix, only `"1"` / `"true"` (case-insensitive after trim) engage the
// override; every other value — including the intuitive "disabled" lexemes
// `"0"` and `""` — leaves the gate active. These tests pin that footgun
// closed at the CLI-integration layer.

#[test]
fn resplit_with_env_var_eq_zero_still_refuses_with_exit_6() {
    // YHSC_ALLOW_DISK_STDOUT=0 must NOT engage the override. The gate
    // refuses the non-TTY stdout exactly as if the var were unset.
    // M-3-2: error message text was updated to name the key-bearing
    // stream — assertion follows.
    let toy = load_fixture("toy_2of3.txt");
    cmd()
        .arg("--resplit")
        .env("YHSC_ALLOW_DISK_STDOUT", "0")
        .write_stdin(toy)
        .assert()
        .code(6)
        .stderr(predicate::str::contains(
            "a key-bearing stream is not a terminal",
        ));
}

#[test]
fn resplit_with_env_var_empty_still_refuses_with_exit_6() {
    // YHSC_ALLOW_DISK_STDOUT="" (set but empty) must NOT engage the
    // override. Pre-fix the empty string sufficed because `var_os` only
    // checked presence; post-fix the trimmed empty string fails the
    // {"1","true"} match and the gate refuses.
    let toy = load_fixture("toy_2of3.txt");
    cmd()
        .arg("--resplit")
        .env("YHSC_ALLOW_DISK_STDOUT", "")
        .write_stdin(toy)
        .assert()
        .code(6)
        .stderr(predicate::str::contains(
            "a key-bearing stream is not a terminal",
        ));
}

// ─────────────────────── M-3-2: --show-key stderr gate ─────────────────
//
// Pre-fix the disk-stdout gate only checked `io::stdout().is_terminal()`.
// An operator running `cmd --show-key < legacy.txt 2> log.txt` (TTY-stdout,
// captured-stderr) passed the gate and the AES key hex landed in `log.txt`.
// Post-fix the gate also refuses when `--show-key` is set and stderr is
// non-TTY. The new error message names which stream is non-TTY so the
// operator can distinguish a `> file` mistake from a `2> log` mistake
// without re-running under strace. Three new tests below pin both halves
// of the fix (stderr gate + clap conflict).

#[test]
fn show_key_with_captured_stderr_refuses_with_exit_6() {
    // assert_cmd captures both stdout AND stderr in the child. With
    // YHSC_ALLOW_DISK_STDOUT unset (cmd() removed it), stderr is non-TTY
    // and the gate must refuse with exit code 6 BEFORE reading stdin.
    // The error message must name the key-bearing stream so the operator
    // sees which redirect leaked.
    let toy = load_fixture("toy_2of3.txt");
    cmd()
        .arg("--show-key")
        .write_stdin(toy)
        .assert()
        .code(6)
        .stderr(predicate::str::contains("key-bearing stream"))
        .stderr(predicate::str::contains("stderr = non-tty (pipe/file)"));
}

#[test]
fn show_key_with_env_var_override_succeeds() {
    // YHSC_ALLOW_DISK_STDOUT=1 + history-safe environment (HISTFILE unset
    // → hist_disabled = true) → the gate accepts the override even though
    // stderr is captured by assert_cmd. R4-3: the dual-knob gate now also
    // requires --i-accept-disk-output on the command line; without it
    // this test would exit 6 even with the env-var set. The converter
    // then runs to completion and prints the unmasked AES key hex on
    // stderr (per H3 mask-by-default with explicit --show-key opt-in).
    let toy = load_fixture("toy_2of3.txt");
    let assert = cmd()
        .arg("--show-key")
        .arg("--i-accept-disk-output")
        .env("YHSC_ALLOW_DISK_STDOUT", "1")
        .write_stdin(toy)
        .assert()
        .success();

    let stderr = String::from_utf8(assert.get_output().stderr.clone()).expect("stderr is utf-8");
    assert!(
        stderr.contains("aes256_key (hex)"),
        "expected unmasked aes256_key line in stderr; got:\n{stderr}"
    );
    // Defence-in-depth: ensure the redacted marker is NOT present when
    // --show-key is honoured.
    assert!(
        !stderr.contains("<redacted"),
        "stderr unexpectedly contains the redaction marker; got:\n{stderr}"
    );
}

#[test]
fn resplit_plus_show_key_is_rejected_by_clap() {
    // M-3-2 part (b): --resplit and --show-key are now clap-conflicting.
    // Pre-fix the pair was allowed (only --inspect-only carried
    // conflicts_with_all over the other two), doubling the leak surface
    // — shares to stdout AND key to stderr in a single invocation. Post-
    // fix clap rejects the combination with its standard "cannot be used
    // with" diagnostic. We assert non-zero + the recognisable fragment
    // rather than pinning clap's exit code (currently 2), so a future
    // clap upgrade doesn't break this test.
    cmd()
        .arg("--resplit")
        .arg("--show-key")
        .assert()
        .failure()
        .stderr(predicate::str::contains("cannot be used with"));
}

// ─────────────────────── R4-4: parse-error redaction ──────────────────
//
// Pre-fix, parse_legacy_share leaked the malformed input back via
// `format!("{s:?}")` style debug-prints — and the malformed input IS
// the secret share material on a typo path. Post-fix the parse-error
// machinery reports only the byte length plus a `content redacted`
// marker (and, for base64 errors, a non-content classification of the
// failure kind). The four tests below pin each leaking call site shut.

#[test]
fn parse_error_redacts_full_share_text() {
    // No-dashes line `XXXXXX` (length 6) trips the splitn(3, '-') shape
    // check at the top of parse_legacy_share. Stderr must NOT contain
    // the input string and MUST contain the length descriptor + the
    // redaction marker.
    cmd()
        .write_stdin("XXXXXX\n")
        .assert()
        .failure()
        .stderr(predicate::str::contains("XXXXXX").not())
        .stderr(predicate::str::contains("length 6"))
        .stderr(predicate::str::contains("content redacted"));
}

#[test]
fn parse_error_redacts_threshold_field() {
    // `AAAAA-2-VGhlb2RvcmU` has a non-numeric threshold of length 5.
    // Stderr must NOT contain `AAAAA` and MUST report the redacted
    // length + marker.
    cmd()
        .write_stdin("AAAAA-2-VGhlb2RvcmU\n")
        .assert()
        .failure()
        .stderr(predicate::str::contains("AAAAA").not())
        .stderr(predicate::str::contains("VGhlb2RvcmU").not())
        .stderr(predicate::str::contains("length 5"))
        .stderr(predicate::str::contains("content redacted"));
}

#[test]
fn parse_error_redacts_index_field() {
    // `2-XXXXX-VGhlb2RvcmU`: threshold parses (2), index field is
    // non-numeric `XXXXX` (length 5). Stderr must NOT contain `XXXXX`
    // and MUST report the redacted length + marker.
    cmd()
        .write_stdin("2-XXXXX-VGhlb2RvcmU\n")
        .assert()
        .failure()
        .stderr(predicate::str::contains("XXXXX").not())
        .stderr(predicate::str::contains("VGhlb2RvcmU").not())
        .stderr(predicate::str::contains("length 5"))
        .stderr(predicate::str::contains("content redacted"));
}

#[test]
fn parse_error_redacts_base64_payload() {
    // `2-1-!!!`: threshold 2 + index 1 both parse, but `!!!` is not in
    // the base64 alphabet — the decode hits InvalidByte. The base64
    // crate's own Display would emit "Invalid symbol 33, offset 0.",
    // leaking the byte value (33 = '!'). Post-fix we report only the
    // failure category + the encoded length, never the byte value.
    cmd()
        .write_stdin("2-1-!!!\n")
        .assert()
        .failure()
        // Forbidden: the literal payload bytes.
        .stderr(predicate::str::contains("!!!").not())
        // Forbidden: the base64 crate's "Invalid symbol N" leak format
        // (which would echo the offending byte's decimal value).
        .stderr(predicate::str::contains("Invalid symbol").not())
        .stderr(predicate::str::contains("Invalid last symbol").not())
        // Forbidden: the decimal byte value of '!' (33).
        .stderr(predicate::str::contains("symbol 33").not())
        // Required: the redacted length + marker + the failure kind.
        .stderr(predicate::str::contains("length 3"))
        .stderr(predicate::str::contains("content redacted"))
        .stderr(predicate::str::contains("invalid base64"));
}

// ─────────────────────── R4-3: dual-knob disk-stdout gate ──────────────
//
// Round 3 shipped a single-knob env-var gate (`YHSC_ALLOW_DISK_STDOUT=1`).
// Round 4 (R4-3) adds a sibling CLI flag `--i-accept-disk-output` and
// requires BOTH knobs to override the disk-stdout refusal. The env-var
// alone, or the CLI flag alone, MUST refuse with exit 6. The history-
// safety gate at `:488-506` is intentionally left single-knob; that
// behaviour is asserted by the existing `env_var_set_with_unsafe_history_
// refuses_with_exit_8` test which deliberately omits the CLI flag.

#[test]
fn resplit_with_env_var_alone_without_flag_refuses_with_exit_6() {
    // R4-3: env-var set, NO --i-accept-disk-output, HISTFILE unset (so
    // the history gate doesn't fire), non-TTY stdout. The dual-knob
    // disk-stdout gate must refuse with exit 6 and the new error
    // message must mention BOTH knobs (env-var + CLI flag).
    let toy = load_fixture("toy_2of3.txt");
    cmd()
        .arg("--resplit")
        .env("YHSC_ALLOW_DISK_STDOUT", "1")
        .write_stdin(toy)
        .assert()
        .code(6)
        .stderr(predicate::str::contains(
            "a key-bearing stream is not a terminal",
        ))
        .stderr(predicate::str::contains("YHSC_ALLOW_DISK_STDOUT=1"))
        .stderr(predicate::str::contains("--i-accept-disk-output"))
        .stderr(predicate::str::contains("BOTH knobs"));
}

#[test]
fn resplit_with_flag_alone_without_env_var_refuses_with_exit_6() {
    // R4-3: --i-accept-disk-output passed, env-var unset, non-TTY stdout.
    // The dual-knob disk-stdout gate must refuse with exit 6 because the
    // env-var half of the dual-knob is not satisfied.
    let toy = load_fixture("toy_2of3.txt");
    cmd()
        .arg("--resplit")
        .arg("--i-accept-disk-output")
        .write_stdin(toy)
        .assert()
        .code(6)
        .stderr(predicate::str::contains(
            "a key-bearing stream is not a terminal",
        ))
        .stderr(predicate::str::contains("YHSC_ALLOW_DISK_STDOUT=1"))
        .stderr(predicate::str::contains("--i-accept-disk-output"));
}

#[test]
fn resplit_with_both_knobs_succeeds() {
    // R4-3: both knobs supplied; HISTFILE unset → hist_disabled = true →
    // history gate doesn't fire. Disk-stdout gate accepts the dual-knob
    // override. The converter re-splits and emits 3 hex-share lines.
    let toy = load_fixture("toy_2of3.txt");
    let assert = cmd()
        .arg("--resplit")
        .arg("--i-accept-disk-output")
        .env("YHSC_ALLOW_DISK_STDOUT", "1")
        .write_stdin(toy)
        .assert()
        .success();

    let out = String::from_utf8(assert.get_output().stdout.clone()).expect("stdout is utf-8");
    let share_lines: Vec<&str> = out
        .lines()
        .filter(|l| {
            // T-X-hex format: starts with `2-<digit>-`, rest is hex.
            l.len() >= 4
                && l.as_bytes()[0] == b'2'
                && l.as_bytes()[1] == b'-'
                && l.as_bytes()[3] == b'-'
                && l.as_bytes()[2].is_ascii_digit()
        })
        .collect();
    assert_eq!(
        share_lines.len(),
        3,
        "expected 3 hex share lines on stdout under dual-knob success path; got: {out:?}"
    );
}

#[test]
fn show_key_with_env_var_alone_without_flag_refuses_with_exit_6() {
    // R4-3 (stderr branch): env-var set, NO --i-accept-disk-output,
    // HISTFILE unset, non-TTY stderr (assert_cmd captures it). The
    // dual-knob disk-stdout gate must refuse with exit 6.
    let toy = load_fixture("toy_2of3.txt");
    cmd()
        .arg("--show-key")
        .env("YHSC_ALLOW_DISK_STDOUT", "1")
        .write_stdin(toy)
        .assert()
        .code(6)
        .stderr(predicate::str::contains(
            "a key-bearing stream is not a terminal",
        ))
        .stderr(predicate::str::contains("--i-accept-disk-output"));
}

#[test]
fn show_key_with_flag_alone_without_env_var_refuses_with_exit_6() {
    // R4-3 (stderr branch): --i-accept-disk-output passed, env-var unset,
    // non-TTY stderr. The dual-knob disk-stdout gate must refuse with
    // exit 6 because the env-var half is missing.
    let toy = load_fixture("toy_2of3.txt");
    cmd()
        .arg("--show-key")
        .arg("--i-accept-disk-output")
        .write_stdin(toy)
        .assert()
        .code(6)
        .stderr(predicate::str::contains(
            "a key-bearing stream is not a terminal",
        ))
        .stderr(predicate::str::contains("YHSC_ALLOW_DISK_STDOUT=1"));
}

#[test]
fn show_key_with_both_knobs_succeeds() {
    // R4-3 (stderr branch): both knobs supplied; HISTFILE unset →
    // history gate doesn't fire; disk-stdout gate accepts. The
    // converter prints the unmasked AES-256 key hex on stderr.
    let toy = load_fixture("toy_2of3.txt");
    let assert = cmd()
        .arg("--show-key")
        .arg("--i-accept-disk-output")
        .env("YHSC_ALLOW_DISK_STDOUT", "1")
        .write_stdin(toy)
        .assert()
        .success();

    let stderr = String::from_utf8(assert.get_output().stderr.clone()).expect("stderr is utf-8");
    assert!(
        stderr.contains("aes256_key (hex)"),
        "expected unmasked aes256_key line in stderr under dual-knob success path; got:\n{stderr}"
    );
    assert!(
        !stderr.contains("<redacted"),
        "stderr unexpectedly contains the redaction marker under --show-key; got:\n{stderr}"
    );
}

#[test]
fn inspect_only_with_dual_override_is_a_noop() {
    // R4-3 Medium residue: --inspect-only never emits key bytes, so the
    // dual-knob is irrelevant. Pass --i-accept-disk-output (no env-var,
    // non-TTY streams) and assert the inspect-only path runs to success
    // exactly as it would without the flag: the marker line appears on
    // stderr and stdout is empty (no key bytes).
    let toy = load_fixture("toy_2of3.txt");
    let assert = cmd()
        .arg("--inspect-only")
        .arg("--i-accept-disk-output")
        .write_stdin(toy)
        .assert()
        .success()
        .stderr(predicate::str::contains("[inspect-only]"))
        .stderr(predicate::str::contains("recovery succeeded"));

    assert_eq!(
        assert.get_output().stdout.len(),
        0,
        "inspect-only with --i-accept-disk-output must still produce no stdout, got {:?}",
        String::from_utf8_lossy(&assert.get_output().stdout)
    );
    // Defence-in-depth: the redacted-key marker must appear on stderr;
    // the flag must NOT cause unmasking under --inspect-only.
    let stderr = String::from_utf8(assert.get_output().stderr.clone()).expect("stderr is utf-8");
    assert!(
        stderr.contains("<redacted"),
        "inspect-only with the dual-knob flag must still redact the AES key; got stderr:\n{stderr}"
    );
}

// ─────────────────────── R4-5: over-determined cross-check ─────────────
//
// The default 2-of-3 yubihsm-setup ceremony has n=3, t=2, so 2t=4 and
// the round-1 H1 disjoint-subset cross-check (n ≥ 2t) is impossible.
// Round 4 (R4-5) closes that hole with a byte-wise over-determined
// Lagrange check: each EXTRA share's payload is predicted from the
// canonical polynomial (defined by shares[..t]) and compared. Single
// byte-flips in the extra shares now exit 4. In the corner case where
// n == t (no redundancy at all) `--resplit` is refused with exit 13
// BEFORE recover() runs — proving by absence-of-key-material that the
// secret never enters process memory on the refusal path.
//
// These tests use the canary `toy_2of3.txt` fixture (52-byte AES-256
// wrap-blob, see src/bin/gen_fixture.rs seed contract). The byte-35
// corruption test requires a payload of at least 36 bytes (smallest
// legitimate AES-128 wrap-blob); the toy fixture's 52 bytes satisfies
// that and exercises the over-determined Lagrange branch end-to-end.

/// Helper: load `toy_2of3.txt` and return its lines as owned strings.
/// This is the canonical synthetic 2-of-3 canary fixture.
fn load_canary_fixture_lines() -> Vec<String> {
    let raw = load_fixture("toy_2of3.txt");
    String::from_utf8(raw)
        .expect("fixture is utf-8")
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| l.to_string())
        .collect()
}

#[test]
fn resplit_on_n_eq_t_refuses_with_exit_13() {
    // R4-5: n == t == 2 (the first 2 lines of a 2-of-3 fixture form a
    // 2-of-2 input). --resplit must be refused with exit 13 BEFORE any
    // recover() call. Critical assertion: the canonical AES-256 hex
    // prefix `29363f04` (the recovered-key prefix that --show-key would
    // print) MUST NOT appear anywhere in stderr — that proves the
    // recover() call was correctly skipped on the refusal path and the
    // secret never entered process memory.
    let lines = load_canary_fixture_lines();
    assert!(
        lines.len() >= 2,
        "fixture must contain at least 2 lines; got {}",
        lines.len()
    );
    let stdin = format!("{}\n{}\n", lines[0], lines[1]);
    let assert = cmd()
        .arg("--resplit")
        .arg("--i-accept-disk-output")
        .env("YHSC_ALLOW_DISK_STDOUT", "1")
        // Match the canary command-line history posture so the history
        // gate doesn't fire (HISTFILE unset → hist_disabled).
        .env_remove("HISTFILE")
        .env("HISTCONTROL", "ignorespace")
        .write_stdin(stdin)
        .assert()
        .code(13);

    let stderr = String::from_utf8(assert.get_output().stderr.clone()).expect("stderr is utf-8");
    let stdout = String::from_utf8(assert.get_output().stdout.clone()).expect("stdout is utf-8");

    // Required: the refusal message must mention the no-redundancy
    // condition and the --inspect-only escape hatch.
    assert!(
        stderr.contains("no redundancy"),
        "refusal stderr must name the no-redundancy condition; got:\n{stderr}"
    );
    assert!(
        stderr.contains("--inspect-only"),
        "refusal stderr must suggest --inspect-only; got:\n{stderr}"
    );

    // Critical: the canonical AES-256 key hex prefix MUST NOT appear in
    // stderr. The toy fixture's recovered key starts with `29363f04...`;
    // if that hex appears here, recover() ran (which the n==t refusal is
    // explicitly meant to prevent — see R4-5 v2 fix #6).
    // `29363f04` = first 4 bytes of toy_2of3.txt's recovered AES-256 key.
    assert!(
        !stderr.contains("29363f04"),
        "secret leaked into stderr on the refusal path — recover() must NOT have run; got:\n{stderr}"
    );
    // Also: no [ok] cross-check / inspect-only markers (those would mean
    // the post-recovery describe_blob path was reached).
    assert!(
        !stderr.contains("[ok]"),
        "refusal path must not print any [ok] marker; got:\n{stderr}"
    );
    assert!(
        !stderr.contains("[inspect-only]"),
        "refusal path must not print the inspect-only marker; got:\n{stderr}"
    );
    // No share lines on stdout either.
    assert_eq!(
        stdout.len(),
        0,
        "refusal path must not write any stdout; got: {stdout:?}"
    );
}

#[test]
fn inspect_only_on_n_eq_t_succeeds() {
    // R4-5: n == t == 2 with --inspect-only is intentionally allowed.
    // The recovery still runs (so the operator can confirm "yes, my t
    // shares decode SOMETHING"), but no key material is emitted; the
    // --resplit refusal does NOT fire here.
    let lines = load_canary_fixture_lines();
    let stdin = format!("{}\n{}\n", lines[0], lines[1]);
    let assert = cmd()
        .arg("--inspect-only")
        .write_stdin(stdin)
        .assert()
        .success()
        .stderr(predicate::str::contains("[inspect-only]"))
        .stderr(predicate::str::contains("recovery succeeded"));

    // Stdout must be empty (no key bytes, no shares).
    assert_eq!(
        assert.get_output().stdout.len(),
        0,
        "inspect-only must produce no stdout, got {:?}",
        String::from_utf8_lossy(&assert.get_output().stdout)
    );
}

#[test]
fn over_determined_passes_on_clean_2_of_3() {
    // R4-5: the canonical 2-of-3 fixture is clean, so the over-determined
    // Lagrange branch must validate successfully and the converter must
    // re-emit shares. Stderr carries the new `[ok] over-determined cross-
    // check passed` marker.
    let raw = load_fixture("toy_2of3.txt");
    let assert = cmd()
        .arg("--resplit")
        .arg("--i-accept-disk-output")
        .env("YHSC_ALLOW_DISK_STDOUT", "1")
        .env_remove("HISTFILE")
        .env("HISTCONTROL", "ignorespace")
        .write_stdin(raw)
        .assert()
        .success()
        .stderr(predicate::str::contains(
            "[ok] over-determined cross-check passed",
        ));

    let out = String::from_utf8(assert.get_output().stdout.clone()).expect("stdout is utf-8");
    let share_lines: Vec<&str> = out
        .lines()
        .filter(|l| {
            l.len() >= 4
                && l.as_bytes()[0] == b'2'
                && l.as_bytes()[1] == b'-'
                && l.as_bytes()[3] == b'-'
                && l.as_bytes()[2].is_ascii_digit()
        })
        .collect();
    assert_eq!(
        share_lines.len(),
        3,
        "expected 3 hex share lines on the clean over-determined success path; got: {out:?}"
    );
}

#[test]
fn over_determined_catches_corruption_at_byte_35() {
    // R4-5 + R12-C-05: take the canonical 2-of-3 fixture, decode share
    // #3, flip byte 35 (interior of the recovered AES-256 key region
    // inside the 52-byte wrap-blob), re-encode, splice back into the
    // input. The over-determined cross-check must fire with exit 4 and
    // the error must be the GENERIC "shares mismatch (one or more)"
    // message — NEITHER the byte position NOR the failing share index
    // is allowed to leak (R4-5 Low residue + R12-C-05 locator-drop:
    // an adversary running repeated probes with different corrupted
    // bytes/shares must learn NO bit beyond "at least one is bad").
    use base64::{engine::general_purpose::STANDARD_NO_PAD, Engine as _};

    let lines = load_canary_fixture_lines();
    assert_eq!(lines.len(), 3, "fixture must be exactly 2-of-3");

    // Decode share #3, flip byte 35, re-encode.
    let parts: Vec<&str> = lines[2].splitn(3, '-').collect();
    assert_eq!(parts.len(), 3, "share #3 must be T-N-base64");
    let mut payload = STANDARD_NO_PAD
        .decode(parts[2].as_bytes())
        .expect("base64 decodes");
    assert!(
        payload.len() > 35,
        "payload must contain offset 35; len = {}",
        payload.len()
    );
    payload[35] ^= 0x01;
    let new_b64 = STANDARD_NO_PAD.encode(&payload);
    let corrupted_line3 = format!("{}-{}-{}", parts[0], parts[1], new_b64);
    let stdin = format!("{}\n{}\n{}\n", lines[0], lines[1], corrupted_line3);

    let assert = cmd()
        .arg("--resplit")
        .arg("--i-accept-disk-output")
        .env("YHSC_ALLOW_DISK_STDOUT", "1")
        .env_remove("HISTFILE")
        .env("HISTCONTROL", "ignorespace")
        .write_stdin(stdin)
        .assert()
        .code(4);

    let stderr = String::from_utf8(assert.get_output().stderr.clone()).expect("stderr is utf-8");
    let stdout = String::from_utf8(assert.get_output().stdout.clone()).expect("stdout is utf-8");

    // Required (R12-C-05): the error message MUST contain the generic
    // mismatch phrasing.
    assert!(
        stderr.contains("over-determined cross-check FAILED") || stderr.contains("shares mismatch"),
        "expected the generic over-determined-mismatch error; got stderr:\n{stderr}"
    );
    // Required: phrasing must mention "one or more" — defines the locator-
    // drop discipline.
    assert!(
        stderr.contains("one or more"),
        "expected `one or more` plural phrasing; got stderr:\n{stderr}"
    );

    // Forbidden (R4-5 Low residue + R12-C-05): NO byte-position leak.
    assert!(
        !stderr.contains("byte 35"),
        "stderr leaked the byte position; got:\n{stderr}"
    );
    assert!(
        !stderr.contains("byte_idx"),
        "stderr leaked the byte_idx variable name; got:\n{stderr}"
    );
    assert!(
        !stderr.contains("offset 35"),
        "stderr leaked the offset; got:\n{stderr}"
    );

    // Forbidden (R12-C-05): NO share-index leak. The corrupt share is
    // index 3 (per parts[1] in the canonical fixture); the new
    // locator-drop discipline means the message must NOT name that
    // index. (We forbid the literal substring "share index 3" — the
    // pre-R12 phrasing — and the bare integer in the
    // "share <n>" context.)
    assert!(
        !stderr.contains("share index 3"),
        "stderr leaked the share index (pre-R12 phrasing); got:\n{stderr}"
    );
    // The integer-3 alone could legitimately appear in other contexts
    // (e.g. "3 extra share(s)" on the success path, but the success
    // markers are not present here — we're on the exit-4 path). The
    // load-bearing locator-drop check is the absence of "share index
    // <integer>" and "share <integer> payload"-style phrasings.
    assert!(
        !stderr.contains("share 3 payload"),
        "stderr leaked the share index via `share N payload`; got:\n{stderr}"
    );
    assert!(
        !stderr.contains("share index 1"),
        "stderr leaked some share index 1; got:\n{stderr}"
    );
    assert!(
        !stderr.contains("share index 2"),
        "stderr leaked some share index 2; got:\n{stderr}"
    );

    // Forbidden: no key bytes / re-emitted shares on stdout (the
    // converter must refuse before reaching the resplit emission loop).
    assert_eq!(
        stdout.len(),
        0,
        "exit-4 path must not write any stdout; got: {stdout:?}"
    );
    // Forbidden: the canonical AES-256 key prefix must NOT appear in
    // stderr (describe_blob's redacted form runs, but --show-key is
    // not set so the literal hex `29363f04` would only appear if the
    // describe path leaked it — defence-in-depth).
    // `29363f04` = first 4 bytes of toy_2of3.txt's recovered AES-256 key.
    assert!(
        !stderr.contains("29363f04"),
        "exit-4 path must not leak the AES key prefix; got:\n{stderr}"
    );
}

// ───────────────────── R12-C-05: full-blob over-determined tests ───────
//
// The pre-R12 byte-wise early-return cross-check could mask LATE-byte
// corruption under specific patterns (a wrong-byte at offset N would
// still be caught, but the *timing* of the failure leaked N via
// repeated invocations). The R12-C-05 rewrite collects the full
// predicted blob first, then constant-time compares — every position is
// folded into the verdict in constant time. The tests below cover:
//
//   • last-byte corruption (boundary case — pre-R12 byte-wise loop
//     traversed all N bytes before failing here, so it caught it, but
//     the rewrite must continue to catch it);
//   • middle-share corruption (shares[t..n], somewhere not the first
//     or last extra share);
//   • multi-share corruption (two simultaneously corrupted extras;
//     a careless rewrite that exited on the FIRST predicted-blob mismatch
//     would still reject, but the constant-time non-short-circuit AND
//     discipline below means EVERY extra is verified independently).
//   • clean 5-of-8 (the over-determined check passes; 3 extras consistent).
//
// All four tests exercise the end-to-end CLI path via assert_cmd, so they
// indirectly verify the production-code rewrite in src/main.rs's n > t
// branch.

/// Build a deterministic 5-of-8 share set over a known 36-byte AES-128
/// blob. Returned as the textual T-N-base64 lines the CLI accepts. Used
/// by the over-determined-5-of-8 tests below.
///
/// R12-C-05 helper: the 5-of-8 ceremony has n=8, t=5 → 3 extra shares.
/// Disjoint-subset cross-check kicks in at n ≥ 2t = 10 so 5-of-8 takes
/// the over-determined branch — exactly the path we need to exercise.
fn build_5_of_8_fixture_lines() -> Vec<String> {
    use base64::{engine::general_purpose::STANDARD_NO_PAD, Engine as _};
    use rand::{rngs::StdRng, Rng, SeedableRng};

    let payload_len = 36usize; // AES-128 wrap blob
    let secret: Vec<u8> = (0..payload_len as u8)
        .map(|i| i.wrapping_mul(11) ^ 0x3C)
        .collect();
    // Deterministic seed so the test is reproducible byte-for-byte.
    let mut rng = StdRng::seed_from_u64(0xC0FF_EE58);
    let threshold: u8 = 5;
    let n: u8 = 8;

    // Generate 4 random coefficients per byte (degree = t-1 = 4).
    let coeffs: Vec<Vec<u8>> = (0..payload_len)
        .map(|_| {
            (0..(threshold as usize - 1))
                .map(|_| rng.r#gen::<u8>())
                .collect()
        })
        .collect();

    // Reference splitter: hand-rolled GF(2^8)/0x11D Lagrange, identical to
    // the one used in src/main.rs's tests::legacy_split. Inlined here so
    // tests/cli.rs doesn't need to cross the lib/bin boundary.
    fn mul_0x11d(a: u8, b: u8) -> u8 {
        let mut acc: u8 = 0;
        let mut a = a;
        let mut b = b;
        for _ in 0..8 {
            let mask = 0u8.wrapping_sub(b & 1);
            acc ^= mask & a;
            let high = a >> 7;
            let high_mask = 0u8.wrapping_sub(high);
            a = (a << 1) ^ (high_mask & 0x1D);
            b >>= 1;
        }
        acc
    }
    let mut shares: Vec<(u8, Vec<u8>)> = (1..=n).map(|x| (x, vec![0u8; payload_len])).collect();
    for (byte_idx, &s) in secret.iter().enumerate() {
        // poly = [secret_byte, c1, c2, c3, c4]
        let mut poly = Vec::with_capacity(threshold as usize);
        poly.push(s);
        for &c in &coeffs[byte_idx] {
            poly.push(c);
        }
        for (x, share) in &mut shares {
            let mut acc: u8 = 0;
            let mut fac: u8 = 1;
            for &coeff in &poly {
                acc ^= mul_0x11d(fac, coeff);
                fac = mul_0x11d(fac, *x);
            }
            share[byte_idx] = acc;
        }
    }

    shares
        .into_iter()
        .map(|(x, payload)| {
            let b64 = STANDARD_NO_PAD.encode(&payload);
            format!("{threshold}-{x}-{b64}")
        })
        .collect()
}

/// Helper: corrupt one byte of one of the share lines in place. Returns
/// the modified Vec. Takes a base64 string and flips byte `byte_idx` of
/// the decoded payload; rewraps. `share_idx` is the position in `lines`
/// (0-based).
fn corrupt_share_byte(
    lines: &[String],
    share_idx: usize,
    byte_idx: usize,
    xor_mask: u8,
) -> Vec<String> {
    use base64::{engine::general_purpose::STANDARD_NO_PAD, Engine as _};
    let mut out: Vec<String> = lines.to_vec();
    let parts: Vec<&str> = out[share_idx].splitn(3, '-').collect();
    assert_eq!(parts.len(), 3, "share lines must be T-N-base64");
    let mut payload = STANDARD_NO_PAD
        .decode(parts[2].as_bytes())
        .expect("base64 decodes");
    payload[byte_idx] ^= xor_mask;
    let new_b64 = STANDARD_NO_PAD.encode(&payload);
    out[share_idx] = format!("{}-{}-{}", parts[0], parts[1], new_b64);
    out
}

#[test]
fn over_determined_detects_corruption_at_byte_0() {
    // R12-C-05: corrupt the FIRST byte of an extra share. The pre-R12
    // byte-wise early-return loop caught this trivially; the new full-
    // blob constant-time compare must continue to catch it. Sanity-check
    // the simplest non-degenerate case before harder ones.
    let lines = load_canary_fixture_lines();
    assert_eq!(lines.len(), 3, "canonical 2-of-3 fixture");
    // Share #3 (lines[2]) is the only extra; flip byte 0.
    let corrupted = corrupt_share_byte(&lines, 2, 0, 0x01);
    let stdin = format!("{}\n{}\n{}\n", corrupted[0], corrupted[1], corrupted[2]);
    let assert = cmd()
        .arg("--resplit")
        .arg("--i-accept-disk-output")
        .env("YHSC_ALLOW_DISK_STDOUT", "1")
        .env_remove("HISTFILE")
        .env("HISTCONTROL", "ignorespace")
        .write_stdin(stdin)
        .assert()
        .code(4);
    let stderr = String::from_utf8(assert.get_output().stderr.clone()).expect("stderr is utf-8");
    assert!(
        stderr.contains("over-determined cross-check FAILED"),
        "byte-0 corruption must trigger the new error; got:\n{stderr}"
    );
}

#[test]
fn over_determined_detects_corruption_at_last_byte() {
    // R12-C-05: corrupt the LAST byte of an extra share. Pre-R12 the
    // byte-wise early-return walked all N bytes before failing here —
    // so it caught it — but the timing of the failure leaked N via
    // repeated invocations. The new full-blob constant-time compare
    // catches the corruption with NO position-dependent timing.
    let lines = load_canary_fixture_lines();
    // Decode share #3 to find payload length (= 52 for AES-256 toy
    // fixture, but compute it instead of hard-coding).
    use base64::{engine::general_purpose::STANDARD_NO_PAD, Engine as _};
    let parts: Vec<&str> = lines[2].splitn(3, '-').collect();
    let payload = STANDARD_NO_PAD
        .decode(parts[2].as_bytes())
        .expect("base64 decodes");
    let last_byte = payload.len() - 1;
    let corrupted = corrupt_share_byte(&lines, 2, last_byte, 0x80);
    let stdin = format!("{}\n{}\n{}\n", corrupted[0], corrupted[1], corrupted[2]);
    let assert = cmd()
        .arg("--resplit")
        .arg("--i-accept-disk-output")
        .env("YHSC_ALLOW_DISK_STDOUT", "1")
        .env_remove("HISTFILE")
        .env("HISTCONTROL", "ignorespace")
        .write_stdin(stdin)
        .assert()
        .code(4);
    let stderr = String::from_utf8(assert.get_output().stderr.clone()).expect("stderr is utf-8");
    assert!(
        stderr.contains("over-determined cross-check FAILED"),
        "last-byte corruption must trigger the new error; got:\n{stderr}"
    );
}

#[test]
fn over_determined_detects_corruption_in_middle_share() {
    // R12-C-05: in a 5-of-8 share set, corrupt one byte of a MIDDLE
    // extra share (not the first extra, not the last extra). With t=5
    // and n=8 there are 3 extras at positions [5, 6, 7]; the middle is
    // index 6 (one-based: share #7 i.e. line index 6). Corrupt byte 17
    // (an interior offset). The new full-blob compare must catch the
    // corruption regardless of WHICH extra share is bad.
    let lines = build_5_of_8_fixture_lines();
    assert_eq!(lines.len(), 8, "5-of-8 fixture must have 8 shares");
    // Sanity: the clean fixture passes (asserted below as
    // over_determined_passes_clean_5_of_8).
    let corrupted = corrupt_share_byte(&lines, 6, 17, 0x42);
    let stdin = corrupted.join("\n") + "\n";
    let assert = cmd()
        .arg("--resplit")
        .arg("--i-accept-disk-output")
        .env("YHSC_ALLOW_DISK_STDOUT", "1")
        .env_remove("HISTFILE")
        .env("HISTCONTROL", "ignorespace")
        .write_stdin(stdin)
        .assert()
        .code(4);
    let stderr = String::from_utf8(assert.get_output().stderr.clone()).expect("stderr is utf-8");
    assert!(
        stderr.contains("over-determined cross-check FAILED"),
        "middle-extra-share corruption must trigger the new error; got:\n{stderr}"
    );
}

#[test]
fn over_determined_detects_multiple_corrupted_shares() {
    // R12-C-05: in a 5-of-8 share set, corrupt TWO different extra
    // shares simultaneously. The new full-blob compare folds every
    // extra share's match-flag into `all_ok` via NON-short-circuit AND
    // — so even when the first extra share is already detected as bad,
    // the second's check still runs (constant-time discipline). A
    // careless rewrite that did `if !first.ok() { return Err }` would
    // silently fail this test if the SECOND corruption happened to
    // perfectly cancel through a polynomial coincidence.
    let lines = build_5_of_8_fixture_lines();
    let one_corrupt = corrupt_share_byte(&lines, 5, 3, 0x55);
    let two_corrupt = corrupt_share_byte(&one_corrupt, 7, 22, 0xAA);
    let stdin = two_corrupt.join("\n") + "\n";
    let assert = cmd()
        .arg("--resplit")
        .arg("--i-accept-disk-output")
        .env("YHSC_ALLOW_DISK_STDOUT", "1")
        .env_remove("HISTFILE")
        .env("HISTCONTROL", "ignorespace")
        .write_stdin(stdin)
        .assert()
        .code(4);
    let stderr = String::from_utf8(assert.get_output().stderr.clone()).expect("stderr is utf-8");
    assert!(
        stderr.contains("over-determined cross-check FAILED"),
        "multi-share corruption must trigger the new error; got:\n{stderr}"
    );
}

#[test]
fn over_determined_passes_clean_5_of_8() {
    // R12-C-05: the deterministic 5-of-8 fixture is clean; the
    // over-determined cross-check must pass and the converter must
    // re-emit shares. Counterpart to the corruption tests above:
    // proves the constant-time compare doesn't FALSE-POSITIVE on
    // clean inputs.
    let lines = build_5_of_8_fixture_lines();
    let stdin = lines.join("\n") + "\n";
    let assert = cmd()
        .arg("--resplit")
        .arg("--i-accept-disk-output")
        .env("YHSC_ALLOW_DISK_STDOUT", "1")
        .env_remove("HISTFILE")
        .env("HISTCONTROL", "ignorespace")
        .write_stdin(stdin)
        .assert()
        .success()
        .stderr(predicate::str::contains(
            "[ok] over-determined cross-check passed",
        ));
    // Sanity: 3 extra shares (n - t = 3) and 8 emitted new-format shares.
    let stderr = String::from_utf8(assert.get_output().stderr.clone()).expect("stderr is utf-8");
    assert!(
        stderr.contains("3 extra share(s)"),
        "expected '3 extra share(s)' in success marker; got:\n{stderr}"
    );
    // Note: emitted-share count check would require parsing the new
    // (post-resplit) wire format; that's covered separately by the
    // canonical fixture round-trip in cli.rs. Here we only assert the
    // over-determined check itself passes.
}

#[test]
fn over_determined_error_message_no_byte_index() {
    // R12-C-05 LOCATOR-DROP DISCIPLINE: corrupt one byte. The error
    // message MUST NOT contain "byte" followed by a numeric index in
    // any form ("byte 35", "byte 5", "byte_idx=N"). The locator-drop
    // is what closes the partial-corruption oracle.
    let lines = load_canary_fixture_lines();
    let corrupted = corrupt_share_byte(&lines, 2, 12, 0x77);
    let stdin = format!("{}\n{}\n{}\n", corrupted[0], corrupted[1], corrupted[2]);
    let assert = cmd()
        .arg("--resplit")
        .arg("--i-accept-disk-output")
        .env("YHSC_ALLOW_DISK_STDOUT", "1")
        .env_remove("HISTFILE")
        .env("HISTCONTROL", "ignorespace")
        .write_stdin(stdin)
        .assert()
        .code(4);
    let stderr = String::from_utf8(assert.get_output().stderr.clone()).expect("stderr is utf-8");
    // Forbidden: "byte <integer>" phrase anywhere in the error context.
    // We use a tight character-window scan: find each "byte" occurrence,
    // skip mandatory whitespace, and assert the next non-whitespace char
    // is NOT a digit. No regex dependency needed — assertion is exact.
    let has_byte_locator = stderr.match_indices("byte").any(|(idx, _)| {
        let tail = &stderr[idx + "byte".len()..];
        let mut chars = tail.chars();
        // Skip whitespace (mandatory between "byte" and the integer).
        let next = chars.find(|c| !c.is_whitespace());
        next.map(|c| c.is_ascii_digit()).unwrap_or(false)
    });
    assert!(
        !has_byte_locator,
        "error message leaked a `byte <N>` locator; got:\n{stderr}"
    );
    // Also forbid the bare `byte_idx` debug-variable name.
    assert!(
        !stderr.contains("byte_idx"),
        "error message leaked `byte_idx`; got:\n{stderr}"
    );
}

#[test]
fn over_determined_error_message_no_share_index_value() {
    // R12-C-05 LOCATOR-DROP DISCIPLINE: the corrupt share's index MUST
    // NOT appear in the failure message. Counterpart to the byte-locator
    // test above: an attacker probing different corruptions must learn
    // only "one or more" — not which one.
    let lines = load_canary_fixture_lines();
    // Corrupt share #3 (line index 2). Then check the error does NOT
    // name "share 3", "share index 3", "share #3", etc.
    let corrupted = corrupt_share_byte(&lines, 2, 8, 0xAA);
    let stdin = format!("{}\n{}\n{}\n", corrupted[0], corrupted[1], corrupted[2]);
    let assert = cmd()
        .arg("--resplit")
        .arg("--i-accept-disk-output")
        .env("YHSC_ALLOW_DISK_STDOUT", "1")
        .env_remove("HISTFILE")
        .env("HISTCONTROL", "ignorespace")
        .write_stdin(stdin)
        .assert()
        .code(4);
    let stderr = String::from_utf8(assert.get_output().stderr.clone()).expect("stderr is utf-8");
    // Required: phrase "one or more" must be present (locator-drop
    // affirmation).
    assert!(
        stderr.contains("one or more"),
        "expected `one or more` phrasing; got:\n{stderr}"
    );
    // Forbidden: any "share <integer>"-style phrase. Per the locator-drop
    // discipline none of "share index N", "share #N", "share N payload"
    // are allowed.
    for forbidden in [
        "share index 1",
        "share index 2",
        "share index 3",
        "share #3",
        "share 3 payload",
    ] {
        assert!(
            !stderr.contains(forbidden),
            "error message leaked share-index via `{forbidden}`; got:\n{stderr}"
        );
    }
}
